uploads = []
generated = []

[[outputs]]
id = "BD8dt9UQdQuXrfoP5Oqmu"
uri = "file://RIDE_backup_20260421.tar.gz"
type = "unspecified"
title = "RIDE Backup - 21 April 2026"

[[outputs]]
id = "n8PIsASpx1mZbfQOhabS5"
uri = "file://RIDE_backup_20260421_v2.tar.gz"
type = "unspecified"
title = "RIDE Backup v2 — 21 April 2026"

[[outputs]]
id = "SekaLUqj4T-FU3AO1t5yT"
uri = "file://RIDE_backup_LENGKAP_20260421.tar.gz"
type = "unspecified"
title = "RIDE Backup LENGKAP — 21 April 2026 (Final)"
